# These are supported funding model platforms
custom: ['https://www.roblox.com/game-pass/87791412','https://www.roblox.com/game-pass/87791454','https://www.roblox.com/game-pass/87791492','https://www.roblox.com/game-pass/87791541']
